name: Commit Style

on:
  pull_request:
    branches: ["**"]
  merge_group:

permissions: {}

jobs:
  check-commit-format:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check commit format
        if: github.event_name == 'pull_request'
        uses: Homebrew/actions/check-commit-format@1e34f2e2acaa766b7efacb8c26352e6abbb023f9 # 2026.09.13.1
        with:
          check_package_commit_format: false
