name: Commit Style

on:
  pull_request:
    branches: ["**"]
  merge_group:

permissions: {}

jobs:
  check-commit-format:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check commit format
        if: github.event_name == 'pull_request'
        uses: Homebrew/actions/check-commit-format@3cdb78d0f62ad29dd32de765782654f4eedea607 # 2026.08.31.1
        with:
          check_package_commit_format: false
