name: Copilot Setup Steps

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@8f3d1ec8a696b3b9d9a6c3696b6c73033cab69e4 # 2026.08.14.1
        with:
          core: true
          cask: true

      - run: brew install-bundler-gems --groups=all

      # install Homebrew formulae we might need
      - uses: Homebrew/actions/cache-homebrew-prefix@8f3d1ec8a696b3b9d9a6c3696b6c73033cab69e4 # 2026.08.14.1
        with:
          install: shellcheck shfmt gh gnu-tar subversion curl
          workflow-key: copilot-setup-steps

      # brew tests doesn't like world writable directories
      - run: sudo chmod -R g-w,o-w /home/linuxbrew/.linuxbrew/Homebrew
